package com.github.dcendents.mybatis.jaxws.db.model.filter;

import com.github.dcendents.mybatis.jaxws.api.Rating;
import com.github.dcendents.mybatis.jaxws.db.model.Language;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FilmFilter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.film
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.film
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.film
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public FilmFilter() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.film
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> languageCriteria;

        protected List<Criterion> ratingCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            languageCriteria = new ArrayList<Criterion>();
            ratingCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getLanguageCriteria() {
            return languageCriteria;
        }

        protected void addLanguageCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            languageCriteria.add(new Criterion(condition, value, "com.github.dcendents.mybatis.jaxws.db.IdTableHandler"));
            allCriteria = null;
        }

        protected void addLanguageCriterion(String condition, Language value1, Language value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            languageCriteria.add(new Criterion(condition, value1, value2, "com.github.dcendents.mybatis.jaxws.db.IdTableHandler"));
            allCriteria = null;
        }

        public List<Criterion> getRatingCriteria() {
            return ratingCriteria;
        }

        protected void addRatingCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            ratingCriteria.add(new Criterion(condition, value, "com.github.dcendents.mybatis.jaxws.db.RatingHandler"));
            allCriteria = null;
        }

        protected void addRatingCriterion(String condition, Rating value1, Rating value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            ratingCriteria.add(new Criterion(condition, value1, value2, "com.github.dcendents.mybatis.jaxws.db.RatingHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || languageCriteria.size() > 0
                || ratingCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(languageCriteria);
                allCriteria.addAll(ratingCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("f.film_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("f.film_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("f.film_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("f.film_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("f.film_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("f.film_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("f.film_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("f.film_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("f.film_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("f.film_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("f.film_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("f.film_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("f.title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("f.title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("f.title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("f.title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("f.title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("f.title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("f.title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("f.title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("f.title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("f.title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("f.title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("f.title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("f.title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("f.title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("f.description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("f.description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("f.description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("f.description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("f.description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("f.description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("f.description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("f.description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("f.description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("f.description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("f.description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("f.description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("f.description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("f.description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("f.release_year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("f.release_year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(int value) {
            addCriterion("f.release_year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(int value) {
            addCriterion("f.release_year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(int value) {
            addCriterion("f.release_year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(int value) {
            addCriterion("f.release_year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(int value) {
            addCriterion("f.release_year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(int value) {
            addCriterion("f.release_year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("f.release_year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("f.release_year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(int value1, int value2) {
            addCriterion("f.release_year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(int value1, int value2) {
            addCriterion("f.release_year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("f.language_id is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("f.language_id is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(Language value) {
            addLanguageCriterion("f.language_id =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(Language value) {
            addLanguageCriterion("f.language_id <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(Language value) {
            addLanguageCriterion("f.language_id >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(Language value) {
            addLanguageCriterion("f.language_id >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(Language value) {
            addLanguageCriterion("f.language_id <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(Language value) {
            addLanguageCriterion("f.language_id <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<Language> values) {
            addLanguageCriterion("f.language_id in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<Language> values) {
            addLanguageCriterion("f.language_id not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(Language value1, Language value2) {
            addLanguageCriterion("f.language_id between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(Language value1, Language value2) {
            addLanguageCriterion("f.language_id not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andRentalDurationIsNull() {
            addCriterion("f.rental_duration is null");
            return (Criteria) this;
        }

        public Criteria andRentalDurationIsNotNull() {
            addCriterion("f.rental_duration is not null");
            return (Criteria) this;
        }

        public Criteria andRentalDurationEqualTo(Short value) {
            addCriterion("f.rental_duration =", value, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationNotEqualTo(Short value) {
            addCriterion("f.rental_duration <>", value, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationGreaterThan(Short value) {
            addCriterion("f.rental_duration >", value, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationGreaterThanOrEqualTo(Short value) {
            addCriterion("f.rental_duration >=", value, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationLessThan(Short value) {
            addCriterion("f.rental_duration <", value, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationLessThanOrEqualTo(Short value) {
            addCriterion("f.rental_duration <=", value, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationIn(List<Short> values) {
            addCriterion("f.rental_duration in", values, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationNotIn(List<Short> values) {
            addCriterion("f.rental_duration not in", values, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationBetween(Short value1, Short value2) {
            addCriterion("f.rental_duration between", value1, value2, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalDurationNotBetween(Short value1, Short value2) {
            addCriterion("f.rental_duration not between", value1, value2, "rentalDuration");
            return (Criteria) this;
        }

        public Criteria andRentalRateIsNull() {
            addCriterion("f.rental_rate is null");
            return (Criteria) this;
        }

        public Criteria andRentalRateIsNotNull() {
            addCriterion("f.rental_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRentalRateEqualTo(BigDecimal value) {
            addCriterion("f.rental_rate =", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateNotEqualTo(BigDecimal value) {
            addCriterion("f.rental_rate <>", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateGreaterThan(BigDecimal value) {
            addCriterion("f.rental_rate >", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("f.rental_rate >=", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateLessThan(BigDecimal value) {
            addCriterion("f.rental_rate <", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("f.rental_rate <=", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateIn(List<BigDecimal> values) {
            addCriterion("f.rental_rate in", values, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateNotIn(List<BigDecimal> values) {
            addCriterion("f.rental_rate not in", values, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f.rental_rate between", value1, value2, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f.rental_rate not between", value1, value2, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("f.length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("f.length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(Short value) {
            addCriterion("f.length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(Short value) {
            addCriterion("f.length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(Short value) {
            addCriterion("f.length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Short value) {
            addCriterion("f.length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(Short value) {
            addCriterion("f.length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(Short value) {
            addCriterion("f.length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<Short> values) {
            addCriterion("f.length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<Short> values) {
            addCriterion("f.length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(Short value1, Short value2) {
            addCriterion("f.length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(Short value1, Short value2) {
            addCriterion("f.length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andReplacementCostIsNull() {
            addCriterion("f.replacement_cost is null");
            return (Criteria) this;
        }

        public Criteria andReplacementCostIsNotNull() {
            addCriterion("f.replacement_cost is not null");
            return (Criteria) this;
        }

        public Criteria andReplacementCostEqualTo(BigDecimal value) {
            addCriterion("f.replacement_cost =", value, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostNotEqualTo(BigDecimal value) {
            addCriterion("f.replacement_cost <>", value, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostGreaterThan(BigDecimal value) {
            addCriterion("f.replacement_cost >", value, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("f.replacement_cost >=", value, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostLessThan(BigDecimal value) {
            addCriterion("f.replacement_cost <", value, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("f.replacement_cost <=", value, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostIn(List<BigDecimal> values) {
            addCriterion("f.replacement_cost in", values, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostNotIn(List<BigDecimal> values) {
            addCriterion("f.replacement_cost not in", values, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f.replacement_cost between", value1, value2, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andReplacementCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f.replacement_cost not between", value1, value2, "replacementCost");
            return (Criteria) this;
        }

        public Criteria andRatingIsNull() {
            addCriterion("f.rating is null");
            return (Criteria) this;
        }

        public Criteria andRatingIsNotNull() {
            addCriterion("f.rating is not null");
            return (Criteria) this;
        }

        public Criteria andRatingEqualTo(Rating value) {
            addRatingCriterion("f.rating =", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotEqualTo(Rating value) {
            addRatingCriterion("f.rating <>", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThan(Rating value) {
            addRatingCriterion("f.rating >", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThanOrEqualTo(Rating value) {
            addRatingCriterion("f.rating >=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThan(Rating value) {
            addRatingCriterion("f.rating <", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThanOrEqualTo(Rating value) {
            addRatingCriterion("f.rating <=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLike(Rating value) {
            addRatingCriterion("f.rating like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotLike(Rating value) {
            addRatingCriterion("f.rating not like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingIn(List<Rating> values) {
            addRatingCriterion("f.rating in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotIn(List<Rating> values) {
            addRatingCriterion("f.rating not in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingBetween(Rating value1, Rating value2) {
            addRatingCriterion("f.rating between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotBetween(Rating value1, Rating value2) {
            addRatingCriterion("f.rating not between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andModifiedOnIsNull() {
            addCriterion("f.last_update is null");
            return (Criteria) this;
        }

        public Criteria andModifiedOnIsNotNull() {
            addCriterion("f.last_update is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedOnEqualTo(Date value) {
            addCriterion("f.last_update =", value, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnNotEqualTo(Date value) {
            addCriterion("f.last_update <>", value, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnGreaterThan(Date value) {
            addCriterion("f.last_update >", value, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnGreaterThanOrEqualTo(Date value) {
            addCriterion("f.last_update >=", value, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnLessThan(Date value) {
            addCriterion("f.last_update <", value, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnLessThanOrEqualTo(Date value) {
            addCriterion("f.last_update <=", value, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnIn(List<Date> values) {
            addCriterion("f.last_update in", values, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnNotIn(List<Date> values) {
            addCriterion("f.last_update not in", values, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnBetween(Date value1, Date value2) {
            addCriterion("f.last_update between", value1, value2, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andModifiedOnNotBetween(Date value1, Date value2) {
            addCriterion("f.last_update not between", value1, value2, "modifiedOn");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesIsNull() {
            addCriterion("f.special_features is null");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesIsNotNull() {
            addCriterion("f.special_features is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesEqualTo(Object value) {
            addCriterion("f.special_features =", value, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesNotEqualTo(Object value) {
            addCriterion("f.special_features <>", value, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesGreaterThan(Object value) {
            addCriterion("f.special_features >", value, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesGreaterThanOrEqualTo(Object value) {
            addCriterion("f.special_features >=", value, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesLessThan(Object value) {
            addCriterion("f.special_features <", value, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesLessThanOrEqualTo(Object value) {
            addCriterion("f.special_features <=", value, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesIn(List<Object> values) {
            addCriterion("f.special_features in", values, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesNotIn(List<Object> values) {
            addCriterion("f.special_features not in", values, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesBetween(Object value1, Object value2) {
            addCriterion("f.special_features between", value1, value2, "specialFeatures");
            return (Criteria) this;
        }

        public Criteria andSpecialFeaturesNotBetween(Object value1, Object value2) {
            addCriterion("f.special_features not between", value1, value2, "specialFeatures");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.film
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.film
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}